language: ruby
script: 'bundle exec rake'
sudo: false
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
services:
  - mongodb
gemfile:
  - gemfiles/7_0.gemfile
  - gemfiles/7_1.gemfile
  - gemfiles/7_2.gemfile

notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
    on_failure: change
    on_success: never
