language: ruby
script: 'bundle exec rake'
sudo: false
rvm:
  - 2.5.1
services:
  - mongodb

notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
    on_failure: change
    on_success: never
